### ISSUE TITLE
setup-grafana.sh waits forever

### ISSUE THREAD

**Issue by gnunn1** [mrsiano/grafana-ocp#1]
in ````setup-grafana.sh```, it creates the application and then checks the status of the pod. However it is expecting to be in the grafana project namespace. This is not the case since it uses ```create namespace``` instead ```create project```. As a result, the script waits forever unless you manually intervene with ```oc project grafana```.

Maybe change ```create namespace``` to ```create project```?

I'm testing with minishift on 3.6

**Comment by mrsiano** [comment]
tnx will fix that.
we have an certain use case to use namespace.

**Comment by mrsiano** [comment]
fixed by #2 
closing

**Comment by gnunn1** [comment]
Unfortunately this is still broken, there is no deployment config so the ``oc rollout status dc/grafana-ocp``` fails. You can't switch it to using the replication controller since there is no status viewer for rc

**Comment by mrsiano** [comment]
there is some changes were made, I've forgot to update the plain yaml.

now we have two yamls.
grafan-ocp.yaml - plain
grafana-ocp-oauth.yaml - secured by oauth.

both of them now should work with dc. 

@gnunn1  please try now and keep me posted
thank in advance

**Comment by gnunn1** [comment]
After you create the namespace you still need to do the ```oc project grafana``` afterwards since subsequent commands require it. 

I'm going to close this issue as I'm switching to the 3.7 prometheus now that I've resolved an issue I was having with it. I really do appreciate your grafana template though and will continue using it, I'll just manage the automation of setting it up as part of an ansible playbook I have.
